version: '2.3'

networks:
  cam:

services:
  frontend:
    build: ./src/Frontend/camFrontend/
    image: cam-frontend
    ports:
      - 10101:4200
    networks:
      - cam

  backend:
    build: ./src/Backend/
    image: cam-backend
    ports:
      - 10100:5000
    networks:
      - cam

  # This should run an elasticsarch container
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
#     container_name: elasticsearch
#     environment:
#       - "node.name=suggestions"
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       - "http.cors.enabled=true"
#       - "http.cors.allow-origin=*"
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     command: bash -c "mkdir -p /var/lib/elasticsearch && tar -C /var/lib/elasticsearch/ -zxvf /es-nodes.tar.gz && bin/elasticsearch"
#     networks:
#       - cam
#     volumes:
#       - ./es-nodes.tar.gz:/es-nodes.tar.gz
  
# volumes:
#   esdata:
#     driver: local
