# Default values for CAM.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

frontend:
#  url: https://demo.webis.de/cam/
  port: 30294
  image: webis/cam-frontend:0.1.3
  replicas: 3

backend:
  url: https://demo.webis.de/cam-api/
  port: 30293
  image: webis/cam-backend:0.1.3
  replicas: 3
  # Paths of models on each host's file system.
  modelsPath: /mnt/ceph/storage/data-in-progress/cam/models/
  useHeuristics: true

elasticsearch:
  host: betaweb001.bw.webis.de
  port: 30920
  username: "" # Override username with `--set elasticsearch.username=EXAMPLE` Helm option.
  password: "" # Override username with `--set elasticsearch.password=EXAMPLE` Helm option.
  indices:
    arguments: depcc
    suggestions: suggestions-index
