apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-elasticsearch-login
type: Opaque
data:
  username: {{ b64enc .Values.elasticsearch.username }}
  password: {{ b64enc .Values.elasticsearch.password }}